{{- if not .Values.externalSecrets.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vomeet.fullname" . }}-db
  labels:
    {{- include "vomeet.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.postgresql.username | default "vomeet" | b64enc | quote }}
  password: {{ .Values.postgresql.password | default "" | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vomeet.fullname" . }}-secrets
  labels:
    {{- include "vomeet.labels" . | nindent 4 }}
type: Opaque
data:
  admin-api-token: {{ .Values.adminApiToken | default "changeme" | b64enc | quote }}
{{- end }}
